apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:  # all the different ports that we want to expose on our pods
    - name: posts # - is an array
      protocol: TCP
      port: 4000 # the port of the NodePort service (*** explain on 4.Orchestrating collection.. folder, movie 17). port and target port can be different
      targetPort: 4000  # on our pod, there is a container that inside him there are application that listening for traffic on port 4000, so we refer to that port as a target port. 
   